### ISSUE TITLE
Network Console Edit/Resend issue UI problem

### ISSUE THREAD

**Issue by minoseah629** [microsoft/edge-devtools-network-console#72]
Window 10 Version 21h1 x64
Edge 92.0.902.73 &
Edge beta 93.0.961.24 

https://techcommunity.microsoft.com/t5/discussions/network-console-edit-resend-issue-ui-problem/m-p/2665888

This applies to both Edge / Edge Beta

In Devtools, I have enabled Network Console.  I right click on a request I want to edit and resend.  But I get this "loading" for an extended time.  Urls in screenshot sanitized 

![ewinhong_1-1629388265405](https://user-images.githubusercontent.com/1980068/130107328-c5d96400-4695-4386-8a9d-7f9c53108dd4.png)

**Comment by minoseah629** [comment]
is anyone going to response?

**Comment by NullQubit** [comment]
It's been over a year since this issue was opened, but for me this problem started happening yesterday. No edge update was done as far as I know.

**Comment by minoseah629** [comment]
I'm still waiting for a response from Microsoft.

**Comment by BloodyRain2k** [comment]
> I'm still waiting for a response from Microsoft.

Might as well wait for the heat death of the universe.
The Network Console has been bothering me for a long while already.

Sometimes when I click "Edit & Resend" it doesn't even create a tab.
Never seems to be a distinct issue, retrying a couple times *eventually* gets it opened.

And this time I got this issue instead, where it *does* open, but doesn't manage to show the textarea for the request's body...

**Comment by mwndl** [comment]
The error started today for me

**Comment by markAtAthena** [comment]
I am seeing the same issue except I don't see any loader, nothing at all changes in the UI after I select edit and resend.

**Comment by captainbrosset** [comment]
Sorry about the silence here. This issue was not on my radar for some reason. 
We have been tracking all of the Network Console issues in this parent issue: https://github.com/MicrosoftEdge/DevTools/issues/224, so please refer to that one for any updates.

The Network Console is an experimental tool which, unfortunately, isn't at the top of our priority list right now. As workarounds, I would suggest using Postman (which this tool was heavily inspired by), or other techniques documented here: https://devtoolstips.org/tips/en/edit-and-resend-network-requests/
